name_title: Morgan Tamayo
phone: (678) 799-6666
location: Atlanta, GA
email: mrgntamayo@gmail.com
twitter: mrgntamayo
github: mrgntamayo
linkedin: morgan-tamayo
bio: >-
    I'm a data scientist, but in my freetime I like to DJ and like to create AI videos.

skills:
  tools:
    - SAS
    - R
    - SQL
    - Python
    - Excel
  methods:
    - Advanced Regression
    - Binary Classification
    - Data Mining
    - K-means Clustering

education:
  - degree: MS in Applied Statistics
    school: Kennesaw State University
    time: Aug 2017-Aug 2019
    description: |
      Describe your study here.

  - degree: BS in Mathematics
    school: Kennesaw State University
    time: Aug 2012-Dec 2016
    description: |
      Describe your study here.

jobs:
  - title: Statistician
    time: Dec 2019-Jan 2024
    place: Epsilon, Atlanta, GA
    tasks:
      - Provided reoccurring market share/flowshare analytics for video & broadband customer behavior.
      - Automated deliverable processes in SAS.
      - Performed ad hoc analyses based on client needs.
  - title: Contractor/Graduate Assistant
    time: May 2018-July 2019
    place: Blue Cross Blue Shield of Tennessee, Chattanooga, TN
    tasks:
      - Cleaned and modeled physician data in Python.
      - Elucidated new factors affecting physician expenses in perinatal care.
  - title: Contractor/Graduate Assistant
    time: Aug 2018-Dec 2018
    place: Unnamed Financial Company, Atlanta, GA
    tasks:
      - Cleaned car loan payment data using R.
      - Developed model to predict which customers would default or pay their loans off in full.
      - Delivered framework for creating risk likelihood scores for customers.
  - title: Graduate Assistant
    time: Jan 2018-May 2018
    place: Kennesaw State University, Kennesaw, GA
    tasks:
      - Analyzed Chemistry students' performance data.
      - Provided analysis of textbook visual representations for a Kennesaw State University professor.

projects:
  - title: Solar Panel Analysis
    time: Fall 2018
    place: Southern Company of Atlanta, GA
    tasks:
      - Lead team using SAS to analyze solar panel and weather data to recommend ideal panel-washing intervals.
      - Presented recommendations showing efficiency improvements in scheduling washes to Southern Company.
  - title: Weather Panel Analysis
    time: Fall 2017
    place: Southern Company of Atlanta, GA
    tasks:
      - Employed SQL to join airport weather data scraped via R with cleaned and organized customer conversion data.
      - Created SAS visualizations (maps and graphs) for final presentation to Southern Company executives.
      - Presented findings detailing correlations between weather data and customer conversion rates.
  - title: Clickstream Analysis
    time: Summer 2016
    place: The Home Depot of Atlanta, GA
    tasks:
      - Worked with .5 terabytes of clickstream data to find insights about customer behavior.
      - Cooperated with The Home Depot on data dictionary definitions.
      - Merged tabled and selected variables using SQL
      - Utilized survival analysis for insight into variables leading to customers leaving the THD website.
      - Presented winning findings and suggestions to The Home Depot executives.
